import { NextResponse } from 'next/server';
import { supabase } from '@/app/lib/supabase';

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const search = searchParams.get('search');

    let query = supabase
      .from('orders')
      .select('*, items:order_items(*, menu_item:menu_items(*))')
      .order('created_at', { ascending: false });

    if (status && status !== 'all') {
      query = query.eq('status', status.toUpperCase());
    }
    if (search) {
      query = query.or(`order_number.ilike.%${search}%,customer_name.ilike.%${search}%`);
    }

    const { data, error } = await query;
    if (error) throw error;

    return NextResponse.json(data);
  } catch (error) {
    console.error('Error fetching orders:', error);
    return NextResponse.json({ error: 'Error fetching orders' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();

    // Insert order (order_number auto-generated by trigger)
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        order_number: '', // trigger will set this
        status: 'PENDING',
        order_type: body.orderType,
        customer_name: body.customerName,
        customer_phone: body.customerPhone,
        customer_address: body.customerAddress || null,
        delivery_note: body.deliveryNote || null,
        subtotal: body.subtotal,
        delivery_fee: body.deliveryFee || 0,
        total: body.total,
        payment_status: 'PENDING',
        payment_method: body.paymentMethod || null,
        notes: body.notes || null,
      })
      .select()
      .single();

    if (orderError) throw orderError;

    // Insert order items
    if (body.items?.length) {
      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(
          body.items.map((item: any) => ({
            order_id: order.id,
            menu_item_id: item.menuItemId,
            quantity: item.quantity,
            unit_price: item.unitPrice,
            total_price: item.quantity * item.unitPrice,
            notes: item.notes || null,
          }))
        );
      if (itemsError) throw itemsError;
    }

    return NextResponse.json(order, { status: 201 });
  } catch (error) {
    console.error('Error creating order:', error);
    return NextResponse.json({ error: 'Error creating order' }, { status: 500 });
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const { id, ...updates } = body;

    const updateData: Record<string, any> = {};
    if (updates.status) updateData.status = updates.status;
    if (updates.paymentStatus) updateData.payment_status = updates.paymentStatus;
    if (updates.paymentMethod) updateData.payment_method = updates.paymentMethod;

    const { data, error } = await supabase
      .from('orders')
      .update(updateData)
      .eq('id', id)
      .select('*, items:order_items(*, menu_item:menu_items(*))')
      .single();

    if (error) throw error;
    return NextResponse.json(data);
  } catch (error) {
    console.error('Error updating order:', error);
    return NextResponse.json({ error: 'Error updating order' }, { status: 500 });
  }
}
